version: '3.8'

services:
  default_database:
    restart: unless-stopped
    image: mongo:latest
    env_file:
      - ./backend/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DEFAULT_DATABASE_USER:?error}
      - MONGO_INITDB_ROOT_PASSWORD=${DEFAULT_DATABASE_PASSWORD:?error}
    ports:
      - "${DEFAULT_DATABASE_PORT:?error}:27017"
    volumes:
      - default_database_data:/data/db

  backend:
    build: ./backend
    depends_on:
      - default_database
    env_file:
      - ./backend/.env

volumes:
  default_database_data:
